services:
  mysql-delivery:
    image: mysql:latest
    restart: always
    container_name: mysql-delivery
    hostname: "mysql-delivery"
    environment:
      MYSQL_DATABASE: 'deliverydb'
      MYSQL_USER: 'deliveryuser'
      MYSQL_PASSWORD: '12345'
      MYSQL_ROOT_PASSWORD: '54321'
    ports:
      - '3308:3306'
    networks:
      - my_network


  msdelivery:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql-delivery
    hostname: "ms-delivery"
    environment:
      MYSQL_HOSTNAME: mysql-delivery
      MYSQL_PORT: 3306
      MSCUSTOMERS_HOSTNAME: ms-customers
      MSCUSTOMERS_PORT: 8081
      MSORDERS_HOSTNAME: ms-orders
      MSORDERS_PORT: 8082
    ports:
      - 8083:8083
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
    external: true